version: '3'

services:
  nginx-service:
    image: nginx:latest
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php82-service
    container_name: nginx-container

  php82-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./app:/var/www/project
    depends_on:
      - mysql8-service
    container_name: php82-container

  mysql8-service:
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: symfony-project
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 9090:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: mysql8-container